version: '3.8'

services:
  # Persistencia de Datos
  db:
    image: postgres:15-alpine
    container_name: db_login_bio_seguro
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - secure_net

  # LÃ³gica de Negocio (Node.js)
  backend:
    build: ./backend
    container_name: backend_login_bio
    ports:
      - "3000:3000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
    depends_on:
      - db
    networks:
      - secure_net

  # Interfaz de Usuario (React)
  frontend:
    build: ./frontend
    container_name: frontend_login_bio
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - secure_net

networks:
  secure_net:
    driver: bridge

volumes:
  db_data: